---
name: concourse

releases:
- name: concourse
  version: "3.12.0"
  url: https://bosh.io/d/github.com/concourse/concourse?v=3.12.0
  sha1: 12746f25cd484bdd9a8ed7151cfed20a142de2fa
- name: garden-runc
  version: "1.13.1"
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.13.1
  sha1: 54cbb89cae1be0708aa056185671665d7f4b2a4f
- name: postgres
  version: "22"
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=22
  sha1: 86a1333122e9cdd051551c83ec26d36f6e325d6c

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: 1GB # We want a persistent disk so that we don't keep fetching new certs on reboot
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: atc
    release: concourse
    properties:
      encryption_key: ((encryption-key))
      external_url: http://localhost/

      token_signing_key: ((token_signing_key))

      basic_auth_username: REPLACE_ME
      basic_auth_password: REPLACE_ME

      postgresql:
        database: atc
        role:
          name: concoursedb
          password: ((postgresql-concourse-password))

  - name: tsa
    release: concourse
    properties:
      host_key: ((tsa_host_key))
      token_signing_key: ((token_signing_key))
      authorized_keys:
      - ((worker_key.public_key))

- name: db
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: postgres
    release: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: atc
        roles:
        - name: concoursedb
          password: ((postgresql-concourse-password))

- name: worker
  instances: 1
  vm_type: default
  stemcell: default
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: worker
    release: concourse
    consumes: {baggageclaim: {from: worker-baggageclaim}}
    properties:
      tsa:
        worker_key: ((worker_key))
  - name: baggageclaim
    release: concourse
    provides: {baggageclaim: {as: worker-baggageclaim}}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

variables:
- name: postgresql-concourse-password
  type: password
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh
- name: encryption-key
  type: password
  options:
    length: 32

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
