---
name: concourse

releases:
- name: concourse
  version: "3.7.0"
  url: https://bosh.io/d/github.com/concourse/concourse?v=3.7.0
  sha1: 20e17e3ac079f1b1a5095329a4fb14de40317bb9
- name: garden-runc
  version: "1.9.0"
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.9.0
  sha1: 77bfe8bdb2c3daec5b40f5116a6216badabd196c
- name: postgres
  version: "22"
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=22
  sha1: 86a1333122e9cdd051551c83ec26d36f6e325d6c

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  vm_type: default
  stemcell: default
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: atc
    release: concourse
    properties:
      external_url: http://localhost/

      token_signing_key: ((token_signing_key))

      basic_auth_username: REPLACE_ME
      basic_auth_password: REPLACE_ME

      postgresql:
        database: atc
        role:
          name: concoursedb
          password: ((postgresql-concourse-password))

  - name: tsa
    release: concourse
    properties:
      host_key: ((tsa_host_key))
      token_signing_key: ((token_signing_key))
      authorized_keys:
      - ((worker_key.public_key))

- name: db
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: postgres
    release: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: atc
        roles:
        - name: concoursedb
          password: ((postgresql-concourse-password))

- name: worker
  instances: 1
  vm_type: default
  stemcell: default
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: groundcrew
    release: concourse
    properties:
      tsa:
        worker_key: ((worker_key))
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

variables:
- name: postgresql-concourse-password
  type: password
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
