---

# Deploy to the Support Network in AWS
- type: replace
  path: /instance_groups/name=alertmanager/networks/name=default/name?
  value: Support

- type: replace
  path: /instance_groups/name=prometheus/networks/name=default/name?
  value: Support

- type: replace
  path: /instance_groups/name=database/networks/name=default/name?
  value: Support

- type: replace
  path: /instance_groups/name=grafana/networks/name=default/name?
  value: Support

- type: replace
  path: /instance_groups/name=nginx/networks/name=default/name?
  value: Support

- type: replace
  path: /instance_groups/name=firehose/networks/name=default/name?
  value: Support

# Update storage volume sizes for persistent services
- type: replace
  path: /instance_groups/name=alertmanager/persistent_disk_type?
  value: 10GB

- type: replace
  path: /instance_groups/name=prometheus/persistent_disk_type?
  value: 10GB

- type: replace
  path: /instance_groups/name=database/persistent_disk_type?
  value: 10GB

- type: replace
  path: /instance_groups/name=grafana/persistent_disk_type?
  value: 10GB

# add monitoring vm_extension to instances (for security groups)
- type: replace
  path: /instance_groups/name=alertmanager/vm_extensions?/-
  value: monitoring

- type: replace
  path: /instance_groups/name=prometheus/vm_extensions?/-
  value: monitoring

- type: replace
  path: /instance_groups/name=database/vm_extensions?/-
  value: monitoring

- type: replace
  path: /instance_groups/name=grafana/vm_extensions?/-
  value: monitoring

- type: replace
  path: /instance_groups/name=nginx/vm_extensions?/-
  value: monitoring

- type: replace
  path: /instance_groups/name=firehose/vm_extensions?/-
  value: monitoring

# deploy small instances
- type: replace
  path: /instance_groups/name=alertmanager/vm_type?
  value: small

- type: replace
  path: /instance_groups/name=prometheus/vm_type?
  value: small

- type: replace
  path: /instance_groups/name=database/vm_type?
  value: small

- type: replace
  path: /instance_groups/name=grafana/vm_type?
  value: small

- type: replace
  path: /instance_groups/name=nginx/vm_type?
  value: small

- type: replace
  path: /instance_groups/name=firehose/vm_type?
  value: small

# replace single nginx instance with 3 instances in a public subnet
# - prometheus
# - alertmanager
# - grafana
# nginx instances have HTTPS termination support thanks to https://github.com/govau/instant-https-boshrelease
- type: replace
  path: /releases/-
  value:
    name: instant-https
    version: 4.3.0
    sha1: 01136e91957de4e5bf4ebc1849aca39b5787e06f
    url: https://github.com/govau/instant-https-boshrelease/releases/download/v4.3.0/instant-https-4.3.0.tgz

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/consumes?
  value:
    nginx: {from: nginx-grafana}

- type: remove
  path: /instance_groups/name=nginx
  value:


- type: replace
  path: /instance_groups/-
  value:
    name: nginx-prometheus
    azs: [ z1, z2, z3 ]
    instances: 1
    vm_type: small
    stemcell: default
    vm_extensions: [monitoring]
    networks:
      - name: Public
        default: [dns, gateway, addressable]
      - name: Internet
        static_ips: [((prometheus_external_ip))]
    jobs:
      - name: nginx
        release: prometheus
        provides:
          nginx: {as: nginx-prometheus}
        properties:
          nginx:
            alertmanager:
              auth_username: admin
              auth_password: ((alertmanager_password))
            prometheus:
              auth_username: admin
              auth_password: ((prometheus_password))
      - name: proxy
        release: instant-https
        properties:
          hostname: ((prometheus_external_hostname))
          contact_email: weboperations@digital.gov.au
          acme_url: https://acme-v01.api.letsencrypt.org/directory
          backends:
            - localhost:9090

- type: replace
  path: /instance_groups/-
  value:
    name: nginx-alertmanager
    azs: [ z1, z2, z3 ]
    instances: 1
    vm_type: small
    stemcell: default
    vm_extensions: [monitoring]
    networks:
      - name: Public
        default: [dns, gateway, addressable]
      - name: Internet
        static_ips: [((alertmanager_external_ip))]
    jobs:
      - name: nginx
        release: prometheus
        provides:
          nginx: {as: nginx-alertmanager}
        properties:
          nginx:
            alertmanager:
              auth_username: admin
              auth_password: ((alertmanager_password))
            prometheus:
              auth_username: admin
              auth_password: ((prometheus_password))
      - name: proxy
        release: instant-https
        properties:
          hostname: ((alertmanager_external_hostname))
          contact_email: weboperations@digital.gov.au
          acme_url: https://acme-v01.api.letsencrypt.org/directory
          backends:
            - localhost:9093

- type: replace
  path: /instance_groups/-
  value:
    name: nginx-grafana
    azs: [ z1, z2, z3 ]
    instances: 1
    vm_type: small
    stemcell: default
    vm_extensions: [monitoring]
    networks:
      - name: Public
        default: [dns, gateway, addressable]
      - name: Internet
        static_ips: [((grafana_external_ip))]
    jobs:
      - name: nginx
        release: prometheus
        provides:
          nginx: {as: nginx-grafana}
        properties:
          nginx:
            alertmanager:
              auth_username: admin
              auth_password: ((alertmanager_password))
            prometheus:
              auth_username: admin
              auth_password: ((prometheus_password))
      - name: proxy
        release: instant-https
        properties:
          hostname: ((grafana_external_hostname))
          contact_email: weboperations@digital.gov.au
          acme_url: https://acme-v01.api.letsencrypt.org/directory
          backends:
            - localhost:3000
