
# Exporter jobs
- type: replace
  path: /instance_groups/name=alertmanager/persistent_disk_type?
  value: 10GB

- type: replace
  path: /instance_groups/name=prometheus/persistent_disk_type?
  value: 10GB

- type: replace
  path: /instance_groups/name=database/persistent_disk_type?
  value: 10GB

- type: replace
  path: /instance_groups/name=grafana/persistent_disk_type?
  value: 10GB
