
# Exporter jobs
- type: replace
  path: /instance_groups/name=alertmanager/vm_extensions?
  value: [monitoring]

- type: replace
  path: /instance_groups/name=prometheus/vm_extensions?
  value: [monitoring]

- type: replace
  path: /instance_groups/name=database/vm_extensions?
  value: [monitoring]

- type: replace
  path: /instance_groups/name=grafana/vm_extensions?
  value: [monitoring]

- type: replace
  path: /instance_groups/name=nginx/vm_extensions?
  value: [monitoring]

- type: replace
  path: /instance_groups/name=firehose/vm_extensions?
  value: [monitoring]
